Header header
bool overloaded
bool alarm
bool lowbattery
string model
float32 total_dose 
int8 units
int8 radiation_type
float32 measurement


#units 
#0 Display unit Sv/h
#1 Display unit Gy/h
#2 Display unit R/h
#3 Display unit cpm
#5 Display unit cps
#6 Display unit Bq
#7 Display unit dpm 
#8 Display unit Bq/cm2
#9 Display unit dps
#10 Display unit rem/h


#Rad types
#0 Unknown
#1 Alpha
#2 Beta
#4 Gamma
#8 Neutrons